language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

branches:
  only:
    - master
script: bundle exec rspec

before_install:
  - gem update --system
  - gem --version
  
env:
  global:
    secure: DzmZmBdrv+tIRNXyqAE1Z7/ksQOmBUThgpeKH2in2vzTZ8q5YAzeQat8YLTW+Z2UcIT7hQMUb+W11rUfPmDCBfcJFn5NaXNowoyHz+CeqJ5XjZtA05o96/8zu6wdh/3d8xfON703SgE7vFGOj3klIqVoBl2ABbk/p2A3sbS7mHs=
